---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "telegraf.fullname" . }}-config
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
data:
  telegraf.conf: {{ .Values.configuration | b64enc }}
