{{- if .Values.services }}
{{- $fullname := include "telegraf.fullname" . -}}
{{- $labels := include "telegraf.labels" . -}}
{{- $selectorLabels := include "telegraf.selectorLabels" . -}}
{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ .name }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    {{- .annotations | toYaml | nindent 4 }}
spec:
  type: {{ .type }}
  {{- if .loadBalancerIP }}
  loadBalancerIP: {{ .loadBalancerIP }}
  {{- end }}
  ipFamilyPolicy: {{ .ipFamilyPolicy }}
  ports:
  {{- range .ports }}
    - port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ default "TCP" .protocol }}
      name: {{ .name }}
  {{- end }}
  selector:
    {{- $selectorLabels | nindent 6 }}
{{- end }}
{{- end }}
